_wandb:
    value:
        cli_version: 0.23.1
        e:
            l63l4zuq5pkw2ld87nvt6lrxpg4qkl3h:
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "241369505792"
                        used: "109654171648"
                email: moeenuddin051@gmail.com
                executable: /home/moeenuddin/Desktop/Deep_learning/dishes/Desi-Food-Classifier-CNN/.venv/bin/python
                git:
                    commit: 4fcc04949cf8ca1ee8d13b583d5af9f44677e5c4
                    remote: https://github.com/MoeenUddin01/Desi-Food-Classifier-CNN.git
                gpu: Quadro P600
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 384
                      memoryTotal: "4294967296"
                      name: Quadro P600
                      uuid: GPU-4c4ce825-d138-5ba7-943c-7ebdfcdf7660
                host: pop-os
                memory:
                    total: "16543408128"
                os: Linux-6.17.9-76061709-generic-x86_64-with-glibc2.35
                program: -m src.pipelines.model_training
                python: CPython 3.10.12
                root: /home/moeenuddin/Desktop/Deep_learning/dishes/Desi-Food-Classifier-CNN
                startedAt: "2026-01-17T06:19:01.065709Z"
                writerId: l63l4zuq5pkw2ld87nvt6lrxpg4qkl3h
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.10.12
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
Batch Size:
    value: 32
Device:
    value: cuda
Epochs:
    value: 10
Learning Rate:
    value: 0.001
Model:
    value: src.model.cnn.CNN
